/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import RoomPanel.phongcon;
import javax.swing.JFrame;

/**
 *
 * @author Vu
 */
public class PanelDSPhong extends javax.swing.JPanel {

    /**
     * Creates new form PanelDSPhong
     */
    public PanelDSPhong() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        excute();
    }
    
    private void excute(){
        phongcon phong1 = new phongcon("001", "Trống");
        phongcon phong2 = new phongcon("001", "Trống");
        phongcon phong3 = new phongcon("001", "Trống");
        phongcon phong4 = new phongcon("001", "Trống");
        phongcon phong5 = new phongcon("001", "Trống");
        phongcon phong6 = new phongcon("001", "Trống");
        phongcon phong7 = new phongcon("001", "Trống");
        phongcon phong8 = new phongcon("001", "Trống");
        phongcon phong9 = new phongcon("001", "Trống");
        phongcon phong10 = new phongcon("001", "Trống");
        phongcon phong11 = new phongcon("001", "Trống");
        phongcon phong12 = new phongcon("001", "Trống");
        phongcon phong13 = new phongcon("001", "Trống");
        addPhong(phong1, phong2, phong3, phong4, phong5, phong6, phong7, phong8,phong9, phong10, phong11, phong12, phong13);
    }
    private void addPhong(phongcon...phong){
        for(int i=0;i<phong.length;i++){
            pnBodyPhongCon.add(phong[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBodyPhongCon = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnBodyPhongCon.setLayout(new java.awt.GridLayout(4, 3, 20, 20));
        add(pnBodyPhongCon, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Chức năng lọc here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        new PanelDSPhong().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnBodyPhongCon;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(int MAXIMIZED_BOTH) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
