/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RoomPanel;

import java.util.ArrayList;

/**
 *
 * @author Vu
 */
public class phongcon extends javax.swing.JPanel {

    /**
     * @return the subPhong
     */
    public ArrayList<phongcon> getSubPhong() {
        return subPhong;
    }

    /**
     * Creates new form phongcon
     */
    private ArrayList<phongcon> subPhong = new ArrayList<>();
    
    public phongcon(String maPhong, String trangThai) {
        initComponents();
        //txtMa.setHorizontalAlignment(JTextField.CENTER);
        txtMa.setText(maPhong);
        txtATrangThai.setText(trangThai);
        for(int i=0;i<subPhong.size();i++){
            this.subPhong.add(subPhong.get(i));
        }
    }

    
    
    
    private void showPhongCon(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i=0;i<subPhong.size();i++){
                    subPhong.get(i).setVisible(true);
                }
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtATrangThai = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMa = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        txtATrangThai.setEditable(false);
        txtATrangThai.setColumns(20);
        txtATrangThai.setRows(5);
        txtATrangThai.setText("Trạng thái here");
        jScrollPane1.setViewportView(txtATrangThai);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);

        txtMa.setEditable(false);
        txtMa.setColumns(5
        );
        txtMa.setRows(5);
        txtMa.setAlignmentX(1.0F);
        txtMa.setAlignmentY(1.0F);
        txtMa.setAutoscrolls(false);
        txtMa.setMargin(new java.awt.Insets(46, 20, 30, 0));
        txtMa.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtMa);

        add(jScrollPane2, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtATrangThai;
    private javax.swing.JTextArea txtMa;
    // End of variables declaration//GEN-END:variables
}
